### ISSUE TITLE
Update environment variable name that the nbexchange notebook plugin uses to talk to nbexchange

### ISSUE THREAD

**Issue by agxs** [edina/nbexchange#25] opened 2020-08-21 14:02 UTC
The notebook plugin uses an environment variable called `NAAS_BASE_URL` and defaults to `https://noteable.edina.ac.uk`. This isn't appropriate for a shared plugin as its a bit too Noteable specific, and it's not accurate really.

This variable should be renamed to NBEXCHANGE_BASE_URL and default to `http://nbexchange:9000`. This is a more accurate name for what the variable is used for.

We need to sync up the noteable-api when this env variable name changes as it's currently passed to notebooks.

**Comment by perllaghu** [comment] 2021-05-24 09:54
This is a duplicate of #26

**Closed by perllaghu** 2021-05-24 09:54 UTC
